apiVersion: v1
kind: Service
metadata:
  name: {{ include "aip.fullname" . }}-app-node
  labels:
    {{- include "aip.labels" . | nindent 4 }}
    app.kubernetes.io/component: app-node
spec:
  type: {{ .Values.appNode.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: app-node
  ports:
    - name: http
      port: {{ .Values.appNode.service.port }}
      targetPort: http
