{{- if and (not .Values.appNode.auth.existingSecret) .Values.appNode.auth.signupSecret .Values.appNode.auth.tokenSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aip.fullname" . }}-auth
  labels:
    {{- include "aip.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_SIGNUP_SECRET: {{ .Values.appNode.auth.signupSecret | quote }}
  APP_TOKEN_SECRET: {{ .Values.appNode.auth.tokenSecret | quote }}
  {{- if .Values.appNode.auth.initialAdmin.email }}
  APP_INITIAL_ADMIN_EMAIL: {{ .Values.appNode.auth.initialAdmin.email | quote }}
  {{- end }}
  {{- if .Values.appNode.auth.initialAdmin.password }}
  APP_INITIAL_ADMIN_PASSWORD: {{ .Values.appNode.auth.initialAdmin.password | quote }}
  {{- end }}
{{- end }}
