{{- if and (not .Values.model.existingSecret) .Values.model.hfToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aip.fullname" . }}-model
  labels:
    {{- include "aip.labels" . | nindent 4 }}
type: Opaque
stringData:
  HF_TOKEN: {{ .Values.model.hfToken | quote }}
{{- end }}
